In [2]:
!pip3 install numpy


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 43.0 kB/s  0:01:34 eta 0:00:06m


In [3]:
!pip3 install pandas


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 38.2 kB/s  0:04:37m0:00:0500:12


In [4]:
!pip3 install matplotlib

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 58.4 kB/s  0:02:36m0:00:0100:06
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 81.3 kB/s  0:00:34 eta 0:00:03
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 113.7 kB/s  0:00:46 eta 0:00:02
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [matplotlib]7 [matplotlib]


In [6]:
import numpy as np


In [7]:
import pandas as pd

In [8]:
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.


In [2]:
import numpy as np

arr1 = np.arange(1, 11)
print(arr1)

arr2 = np.random.randint(1, 10, size=(3, 3))
print(arr2)

print("Sum:", arr1.sum())
print("Mean:", arr1.mean())
print("Max:", arr1.max())

arr_mult = arr1 * 2
print(arr_mult)

arr_replaced = arr1.copy()
arr_replaced[arr_replaced > 5] = 0
print(arr_replaced)

[ 1  2  3  4  5  6  7  8  9 10]
[[7 1 1]
 [2 8 5]
 [8 4 7]]
Sum: 55
Mean: 5.5
Max: 10
[ 2  4  6  8 10 12 14 16 18 20]
[1 2 3 4 5 0 0 0 0 0]
